=== dejano/NiceHead/CentralnaBanka/WEB-INF/xsd/cb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://www.ftn.uns.ac.rs/xws/xsd/cb"
	xmlns:cb="http://www.ftn.uns.ac.rs/xws/xsd/cb"
	xmlns:cmn="http://www.ftn.uns.ac.rs/xws/xsd/common" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="2.0" xmlns:mt102="http://www.ftn.uns.ac.rs/xws/xsd/mt102">

	<xs:annotation>
		<xs:appinfo>
			<jxb:globalBindings collectionType="java.util.ArrayList"/>
			<jxb:schemaBindings>
				<jxb:package name="rs.ac.uns.ftn.xws.domain"/>
			</jxb:schemaBindings>
		</xs:appinfo>
	</xs:annotation>

	<xs:import namespace="http://www.ftn.uns.ac.rs/xws/xsd/common" schemaLocation="common.xsd"/>
	<xs:import namespace="http://www.ftn.uns.ac.rs/xws/xsd/mt102" schemaLocation="mt102.xsd"/>
	<xs:complexType name="Bank">
		<xs:sequence>
			<xs:element name="swiftCode" type="cmn:SwiftCode"/>
			<xs:element name="bankClearingAccountNumber" type="cmn:AccountNumber"/>
			<xs:element name="wsUrl" type="xs:string"/>
			<xs:element name="balance">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BanksData">
		<xs:sequence>
			<xs:element name="banks">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" minOccurs="0" name="bank" type="cb:Bank">
							<xs:unique name="unique-bank">
								<xs:selector xpath="bank"/>
								<xs:field xpath="swiftCode"/>
								<xs:field xpath="bankClearingAccountNumber"/>
								<xs:field xpath="wsUrl"/>
							</xs:unique>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="MessageIdData">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:totalDigits value="50"/>
			<xs:pattern value="[0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ClearingData">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="mt102" type="mt102:Mt102"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="bank" type="cb:Bank"/>
	<xs:element name="banksData" type="cb:BanksData"> </xs:element>
	<xs:element name="messageIdData" type="cb:MessageIdData"/>
	<xs:element name="clearingData" type="cb:ClearingData"/>
</xs:schema>

=== dejano/NiceHead/CentralnaBanka/bin/banks.xml
<?xml version="1.0" encoding="UTF-8"?>
<banksData xmlns:cb="http://www.ftn.uns.ac.rs/xws/xsd/cb"
	xmlns:cmn="http://www.ftn.uns.ac.rs/xws/xsd/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ftn.uns.ac.rs/xws/xsd/cb cb.xsd ">
	<banks>
		<bank>
			<swiftCode>CONARS22</swiftCode>
			<bankClearingAccountNumber>111-1111111111111-11</bankClearingAccountNumber>
			<wsUrl>wsUrl</wsUrl>
			<balance>0</balance>
		</bank>
		<bank>
			<swiftCode>CONARS23</swiftCode>
			<bankClearingAccountNumber>111-1111111111111-12</bankClearingAccountNumber>
			<wsUrl>wsUrl</wsUrl>
			<balance>0</balance>
		</bank>
	</banks>
</banksData>

=== dejano/NiceHead/CentralnaBanka/src/main/resources/banks.xml
<?xml version="1.0" encoding="UTF-8"?>
<banksData xmlns:cb="http://www.ftn.uns.ac.rs/xws/xsd/cb"
	xmlns:cmn="http://www.ftn.uns.ac.rs/xws/xsd/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ftn.uns.ac.rs/xws/xsd/cb ../../../WEB-INF/xsd/cb.xsd ">
	<bank>
		<swiftCode>CONARS22</swiftCode>
		<bankClearingAccountNumber>111-1111111111111-11</bankClearingAccountNumber>
		<wsUrl>http://localhost:8080/banka</wsUrl>
		<balance>100000</balance>
	</bank>
	<bank>
		<swiftCode>CONARS23</swiftCode>
		<bankClearingAccountNumber>111-1111111111111-12</bankClearingAccountNumber>
		<wsUrl>http://localhost:8080/banka</wsUrl>
		<balance>10000</balance>
	</bank>
</banksData>

=== dejano/NiceHead/CentralnaBanka/src/main/resources/banksData.xml
<?xml version="1.0" encoding="UTF-8"?>
<cb:banksData xmlns:cb="http://www.ftn.uns.ac.rs/xws/xsd/cb"
	xmlns:cmn="http://www.ftn.uns.ac.rs/xws/xsd/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ftn.uns.ac.rs/xws/xsd/cb ../../../WEB-INF/xsd/cb.xsd">
	<cb:bank>
		<cb:swiftCode>CONARS22</cb:swiftCode>
		<cb:bankClearingAccountNumber>111-1111111111111-11</cb:bankClearingAccountNumber>
		<cb:wsUrl>http://localhost:8081/banka1</cb:wsUrl>
		<cb:balance>100000</cb:balance>
	</cb:bank>
	<cb:bank>
		<cb:swiftCode>CONARS23</cb:swiftCode>
		<cb:bankClearingAccountNumber>111-1111111111111-12</cb:bankClearingAccountNumber>
		<cb:wsUrl>http://localhost:8080/banka2</cb:wsUrl>
		<cb:balance>10000</cb:balance>
	</cb:bank>
</cb:banksData>
