=== dejano/NiceHead/Banka/WEB-INF/xsd/mpb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns:mpb="http://www.ftn.uns.ac.rs/xws/xsd/mpb"
	targetNamespace="http://www.ftn.uns.ac.rs/xws/xsd/mpb"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0"
	xmlns:cmn="http://www.ftn.uns.ac.rs/xws/xsd/common">

	<xs:annotation>
		<xs:appinfo>
			<jxb:globalBindings collectionType="java.util.ArrayList"/>
			<jxb:schemaBindings>
				<jxb:package name="rs.ac.uns.ftn.xws.domain"/>
			</jxb:schemaBindings>
		</xs:appinfo>
	</xs:annotation>

	<xsd:import namespace="http://www.ftn.uns.ac.rs/xws/xsd/common"
		schemaLocation="../xsd/common.xsd"/>


	<xs:complexType name="Company">
		<xs:sequence>
			<xs:element name="accountNumber" type="cmn:AccountNumber"/>
			<xs:element name="balance" type="xs:decimal"/>
			<xs:element name="reservedAmount" type="xs:decimal"/>
			<xs:element name="wsUrl" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CompanyData">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="company" type="mpb:Company"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element abstract="false" name="companyData" type="mpb:CompanyData"/>
</xs:schema>

=== dejano/NiceHead/Banka/bin/companyData.xml
<?xml version="1.0" encoding="UTF-8"?>
<companyData xmlns:cmn="http://www.ftn.uns.ac.rs/xws/xsd/common"
	xmlns:mpb="http://www.ftn.uns.ac.rs/xws/xsd/mpb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ftn.uns.ac.rs/xws/xsd/mpb ../../../WEB-INF/xsd/mpb.xsd ">
	<company>
		<accountNumber>222-2222222222222-22</accountNumber>
		<balance>1000.0</balance>
		<reservedAmount>1000.0</reservedAmount>
		<wsUrl>foo</wsUrl>
	</company>
	<company>
		<accountNumber>223-2222222222222-22</accountNumber>
		<balance>1000.0</balance>
		<reservedAmount>1000.0</reservedAmount>
		<wsUrl>bar</wsUrl>
	</company>
</companyData>
