=== dejano/NiceHead/src/main/java/rs/ac/uns/ftn/xmlbsep/beans/jaxb/generated/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.ftn.uns.ac.rs/xmlbsep/company/invoice"
           xmlns:inv="http://www.ftn.uns.ac.rs/xmlbsep/company/invoice">

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="120"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="discount">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="percentage">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="5"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="value">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="12"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="unit">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="6"/>
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="10"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="quantity">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="10"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="taxes">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="total_price">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="price_with_discount">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:totalDigits value="3"/>
                        <xs:pattern value="[0-9]+"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="invoice">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" name="invoice_header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="supplier" type="inv:Tsupplier_buyer"/>
                            <xs:element name="buyer" type="inv:Tsupplier_buyer"/>
                            <xs:element name="bill" type="inv:Tbill"/>
                            <xs:element name="price">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="services">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:totalDigits value="15"/>
                                                    <xs:fractionDigits value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="goods">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:fractionDigits value="2"/>
                                                    <xs:totalDigits value="15"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="total_taxes">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:totalDigits value="15"/>
                                                    <xs:fractionDigits value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="total_discount">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:totalDigits value="15"/>
                                                    <xs:fractionDigits value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="total">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:totalDigits value="15"/>
                                                    <xs:fractionDigits value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="payment">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="currency" type="inv:Tcurrency"> </xs:element>
                                        <xs:element name="amount">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:totalDigits value="15"/>
                                                    <xs:fractionDigits value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="account_number">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                                                    <xs:length value="20"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="inv:item"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Tsupplier_buyer">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="255"/>
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="address">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="pib">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="11"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="Tnumber6">
        <xs:restriction base="xs:int">
            <xs:totalDigits value="6"/>
            <xs:pattern value="[0-9]+"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Tbill">
        <xs:simpleContent>
            <xs:extension base="inv:Tnumber6">
                <xs:attribute name="date" use="required" type="xs:date"> </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="Tstring3">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Tcurrency">
        <xs:simpleContent>
            <xs:extension base="inv:Tstring3">
                <xs:attribute name="date" use="required" type="xs:date"> </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== dejano/NiceHead/src/main/resources/xml.samples/invoice/invoice3.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns="http://www.ftn.uns.ac.rs/xmlbsep/company/invoice"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xmlbsep/company/invoice file:/C:/Users/dejan/Documents/School/8%20semestar/company/src/main/resources/xsd/invoice.xsd"  id="123">
    <invoice_header>
        <supplier>
            <name>name0</name>
            <address>address0</address>
            <pib>pib0</pib>
        </supplier>
        <buyer>
            <name>name1</name>
            <address>address1</address>
            <pib>pib1</pib>
        </buyer>
        <bill date="2006-05-04">500000</bill>
        <price>
            <services>0.00</services>
            <goods>0.00</goods>
            <total_taxes>0.00</total_taxes>
            <total_discount>0.00</total_discount>
            <total>0.00</total>
        </price>
        <payment>
            <currency date="2006-05-04">cur</currency>
            <amount>0.00</amount>
            <account_number>000-0000000000000-00</account_number>
        </payment>
    </invoice_header>
    <item id="500">
        <name>name2</name>
        <discount>
            <percentage>0.00</percentage>
            <value>0.00</value>
        </discount>
        <unit>
            <name>name3</name>
            <price>0.00</price>
        </unit>
        <quantity>0.00</quantity>
        <taxes>0.00</taxes>
        <total_price>0.00</total_price>
        <price_with_discount>0.00</price_with_discount>
    </item>
    <item id="500">
        <name>name4</name>
        <discount>
            <percentage>0.00</percentage>
            <value>0.00</value>
        </discount>
        <unit>
            <name>name5</name>
            <price>0.00</price>
        </unit>
        <quantity>0.00</quantity>
        <taxes>0.00</taxes>
        <total_price>0.00</total_price>
        <price_with_discount>0.00</price_with_discount>
    </item>
</invoice>
