=== dejano/NiceHead/src/main/java/rs/ac/uns/ftn/xmlbsep/beans/jaxb/generated/partner/partner.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/xmlbsep/company/invoice"
    xmlns:prt="http://www.ftn.uns.ac.rs/xmlbsep/company/invoice">

    <xs:element name="partner">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="address">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="name">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="pib">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="11"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="base_rest_url">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="account">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="account_number">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                                        <xs:length value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dejano/NiceHead/src/main/resources/xml.samples.partner/partner2.xml
<?xml version="1.0" encoding="UTF-8"?>
<partner xmlns="http://www.ftn.uns.ac.rs/xmlbsep/partner"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xmlbsep/partner file:/C:/Users/dejan/Documents/School/8%20semestar/company/src/main/resources/xsd/partner.xsd">
    <address>address0</address>
    <name>name0</name>
    <pib>pib0</pib>
    <base_rest_url>base_rest_url0</base_rest_url>
    <account>
        <account_number>000-0000000000000-00</account_number>
    </account>
    <account>
        <account_number>000-0000000000000-00</account_number>
    </account>
</partner>
